<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE students[

        <!ELEMENT students (student+)>
        <!ELEMENT student (name,age)>
        <!ELEMENT name (#PCDATA)>
        <!ELEMENT age (#PCDATA)>
        <!ATTLIST student sn CDATA #REQUIRED>
        ]>


<students>
    <student sn="01">
        <name>张三</name>
        <age>18</age>
    </student>
    <student sn="02">
        <name>李四</name>
        <age>120</age>
    </student>
</students>